server:
  scale: 3
   health_check:
     port: 3000
     request_line: GET /ping HTTP/1.1
     interval: 8000
     initializing_timeout: 10000
     response_timeout: 2000
     healthy_threshold: 2
     unhealthy_threshold: 4
     strategy: recreate
